### ISSUE TITLE
There is no try

### ISSUE THREAD

**Issue by capicue** [Bogdanp/elm-combine#10]
I'm encountering difficulties with `manyTill` that I believe are due to an absence of a `try` combinator that doesn't consume any input on error.

As an example, I would expect the following to return the list `['a', ' ', 'b', ' ', 'c']`, but it returns `['a', 'b', 'c']`.
```elm
parse (manyTill anyChar ((many space) *> eol)) "a b c\n"
-->  (Ok ['a','b','c'],{ input = "", position = 7 })
-->      : ( Combine.Result (List Char), Combine.Context )
```

**Comment by Bogdanp** [comment]
Thanks for reporting the issue!

This was actually a bug in `manyTill`: it incorrectly passed the `end` parser's failure context to the `p` parser. `try` should not be necessary in `Combine` at this point because all its combinators favor backtracking on error.

**Comment by capicue** [comment]
Great, thanks so much!

I prefer the backtracking-on-error behavior. Glad it went this way.
