### ISSUE TITLE
Elm 0.17

### ISSUE THREAD

**Issue by saschatimme** [Bogdanp/elm-combine#12]
There is a new Elm version http://elm-lang.org/blog/farewell-to-frp and the lazy dependency doesn't work anymore, but there is a new (official) fork of it https://github.com/elm-lang/lazy. But just replacing the dependency and updating the module syntax was at least in my case not sufficient. I get a runtime exception at the first execution.

**Comment by Bogdanp** [comment]
I've pushed a 0.17-compatible version. Let me know if you run into any issues.
