### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'ctor' of undefined" when using Combine.parens

### ISSUE THREAD

**Issue by Dobiasd** [Bogdanp/elm-combine#14]
Hi,

this [minimal example](https://gist.github.com/Dobiasd/78a0e89064e23685541b61ffdcff4d9f) produces [that error](http://i.imgur.com/p7FfRmM.png). Here is my [elm-package.json](https://gist.github.com/Dobiasd/a4ef84571d878e6eb115d2833bfaaf45)

Is this a bug, or is the error on my side? If I set

    stringToParse = "a"
everything works fine.

**Comment by Bogdanp** [comment]
Hi!

The issue is you are eagerly calling `dataParser` in its body.

Check out http://package.elm-lang.org/packages/Bogdanp/elm-combine/2.2.1/Combine#rec and https://github.com/Bogdanp/elm-combine/issues/7#issuecomment-177468446 for a more in-depth explanation.

**Comment by Dobiasd** [comment]
Argh, no lazyness, of course. Thank you very much, and sorry for bothering.
