### ISSUE TITLE
Cannot be used with UrlParser

### ISSUE THREAD

**Issue by sporto** [Bogdanp/elm-combine#18]
Please see https://github.com/evancz/url-parser/issues/17#issuecomment-260776426

In my project I use https://github.com/Bogdanp/elm-time which depends on elm-combine

At the moment this library and UrlParser cannot coexist in a project because `<?>`.

https://github.com/elm-lang/elm-compiler/issues/1096

This issue with infix operators being global needs to be fixed in the compiler but for the meantime it would be great if this conflict could be fixed by changing the infix operator that elm-combine defines.

**Comment by Bogdanp** [comment]
Clearly this means you should use [elm-route](https://travis-ci.org/Bogdanp/elm-route) instead 😜. I've removed the fixity annotation for `<?>` and published `3.1.1` which _should_ fix this issue. I'm not sure if I need to publish an updated version of `elm-time` yet.

**Comment by Bogdanp** [comment]
I was able to successfully compile `url-parser-deps` so I think the issue is resolved.
