### ISSUE TITLE
Cannot be used with Fresheyeball/elm-return

### ISSUE THREAD

**Issue by roSievers** [Bogdanp/elm-combine#19]
Just as in #18, the 6.0.0 update to elm-return introduces an infix precedence that is incompatible with elm-combine. I'll also report this to and hope you two find a way to get the packages compatible again.

Bug at elm-return: https://github.com/Fresheyeball/elm-return/issues/6
For everyone else reading along, this triggers https://github.com/elm-lang/elm-compiler/issues/1096

**Comment by Bogdanp** [comment]
It looks like this was fixed in `elm-return` so I'm closing this issue.
