### ISSUE TITLE
Why not use Result from core?

### ISSUE THREAD

**Issue by igrep** [Bogdanp/elm-combine#5]
Why is the type `Combine.Result` defined as

```elm
type Result res
  = Done res
  | Fail (List String)
```

instead of

```elm
type alias Result res = Result.Result (List String) res
```

using the `Result.Result` from the core even though they are obviously isomorphic?
It's annoying to convert every time calling `parse`!

**Comment by Bogdanp** [comment]
I'll make this change in the coming weeks. The reason I went with a new ADT initially is because I thought I would end up creating more result states that just those two.
