### ISSUE TITLE
Runtime crash with simple recursive grammar

### ISSUE THREAD

**Issue by newlandsvalley** [Bogdanp/elm-combine#7]
I'm still finding this a wonderful parser.  However, I've managed to crash the elm runtime with the error - cannot read property 'ctor' of undefined.  I'm simply trying to parse lists of characters between brackets where the brackets can be nested - for example (AB (C D) E F). See this gist - https://gist.github.com/newlandsvalley/96dabd17480609ab4000. If I remove from the grammar the possibility of brackets being nested, the problem goes away.

It's strange because there's no such problem with your Calc example.

I suspect this is an Elm problem rather than a Combine one, but I thought I'd better post it here first.

**Comment by Bogdanp** [comment]
Elm is eagerly evaluated so in your example `slur` and `slurContent` end up creating a circular dependency that gets evaluated as soon as the output JS does, which means one function ends up calling the constructor of the other before the other is defined :). You can get around this using the `rec` combinator. For example you can rewrite `slurContent` to

```Elm
slurContent : Parser Music
slurContent = rec <| \() -> choice [note , slur, spacer]
```

thich should fix your problem.

**Comment by newlandsvalley** [comment]
Ah, of course - what wonderful support you give.  Fixes the problem immediately.

**Comment by alech** [comment]
I had a very similar issue and the "rec <| \() ->" trick solved it for me, too. I was wondering if this could be documented more clearly, for example in the documentation of "rec", since more people might stumble upon this.
