### ISSUE TITLE
`many` does not halt on successful but unaffected contexts

### ISSUE THREAD

**Issue by freakingawesome** [Bogdanp/elm-combine#8]
Some parsers, like `while` or `many` can return `Ok` without consuming any input. When such a parser  is used as the input to `many`, the program will fail to halt. Here is a contrived example that will not halt:

    parse (many <| while ((/=) 'c')) "abc"

**Comment by Bogdanp** [comment]
Thanks for reporting and fixing the issue! :)

I've published version `2.0.1` of the package with your fix.
